name: Build and deploy container app to Azure Web App - nestor-api

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Create annotation for build error
        run: echo ${{ secrets.test }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to container registry
        uses: docker/login-action@v2
        with:
          registry: https://nestorapi.azurecr.io/
          username: ${{ secrets.AzureAppService_ContainerUsername_63b7194404744080bcb7cd7355a89786 }}
          password: ${{ secrets.AzureAppService_ContainerPassword_a450e7c310f144649acae1cbe80ed58a }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: nestorapi.azurecr.io/go-api:${{ github.sha }}
          file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'nestor-api'
          slot-name: 'production'
          publish-profile: ${{ secrets.AzureAppService_PublishProfile_e1364572c8cd4994ab36991a45e1a0bb }}
          images: 'nestorapi.azurecr.io/go-api:${{ github.sha }}'
